#!/bin/bash
cd "$(dirname "$0")"

ZIPNAME="COS214_Prac2.zip"
rm -f "$ZIPNAME"

zip -j "$ZIPNAME" makefile \
  $(find . -path ./build -prune -o \
      \( -name '*.h' -o -name '*.cpp' \) -print)

echo "Created $ZIPNAME"
unzip -l "$ZIPNAME"